name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    name: "CI: Check Project"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Check index.html
        run: |
          if [ ! -f index.html ]; then
            echo "index.html not found!"
            exit 1
          fi

  CD:
    name: "CD: Deploy"
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
